# Generated by Django 5.2.17 on 2026-08-10 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='journey',
            name='simpleshop_product_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('source_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('source_order_number', models.CharField(blank=True, default='', max_length=64)),
                ('source_product_id', models.CharField(blank=True, default='', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('opened_via', models.CharField(choices=[('simpleshop_webhook', 'SimpleShop webhook'), ('admin', 'Manually opened (admin)')], default='admin', max_length=32)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics', to='assessments.journey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'diagnostics',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='diagnostics',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='assessments.diagnostics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='diagnostics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.diagnostics'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='testsubmission',
            index=models.Index(fields=['diagnostics', 'test'], name='assessments_diagnos_c596d9_idx'),
        ),
    ]
