# Generated by Django 5.2.17 on 2026-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_reword_ambiguous_snapshot_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfeedback',
            name='email_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminfeedback',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
