# Generated by Django 5.2.17 on 2026-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_adminfeedback_email_body_adminfeedback_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfeedback',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
