# Generated by Django 5.2.17 on 2026-10-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_adminfeedback_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response_state',
            field=models.CharField(choices=[('answered', 'Answered'), ('not_applicable', 'Not applicable'), ('skipped', 'Skipped')], default='answered', max_length=16),
        ),
        migrations.AddField(
            model_name='journey',
            name='requires_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='reflection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('snapshot', 'Snapshot (Likert scale, aggregated)'), ('mapping', 'Mapping (open-ended, no aggregation)'), ('reflection', 'Reflection (paired 1-7 ratings with N/A and skip, per-domain means)')], max_length=32),
        ),
    ]
